apiVersion: configplane.juniper.net/v1alpha1
kind: ApiServer
metadata:
  name: contrail-k8s-apiserver
  namespace: contrail
spec:
  common:
    platform: ocp
    containers:
    - image: svl-artifactory.juniper.net/atom-docker/cn2/bazel-build/dev/contrail-k8s-apiserver:latest
      name: contrail-k8s-apiserver
    nodeSelector:
      node-role.kubernetes.io/master: ""
