apiVersion: controlplane.juniper.net/v1alpha1
kind: Control
metadata:
  name: contrail-control
  namespace: contrail
spec:
  common:
    replicas: 1
    containers:
    - image: svl-artifactory.juniper.net/atom-docker/cn2/bazel-build/dev/contrail-control:master-3100
      name: contrail-control
    - image: svl-artifactory.juniper.net/atom-docker/cn2/bazel-build/dev/contrail-telemetry-exporter:latest
      name: contrail-control-telemetry-exporter
    initContainers:
    - image: svl-artifactory.juniper.net/atom-docker/cn2/bazel-build/dev/contrail-init:mhenkel_CN2-3779-4
      name: contrail-init
    nodeSelector:
      node-role.kubernetes.io/master: ""