apiVersion: dataplane.juniper.net/v1alpha1
kind: Vrouter
metadata:
  name: contrail-vrouter-nodes
  namespace: contrail
spec:
  agent:
    virtualHostInterface:
      physicalInterface: "enp2s0"
    gateway: "10.0.0.1"
  common:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/master
              operator: NotIn
              values:
              - ""
    containers:
    - image: svl-artifactory.juniper.net/atom-docker/cn2/bazel-build/dev/contrail-vrouter-agent:ocp
      name: contrail-vrouter-agent
    - image: svl-artifactory.juniper.net/atom-docker/cn2/bazel-build/dev/contrail-init:enable_second_interface
      name: contrail-watcher
    - image: svl-artifactory.juniper.net/atom-docker/cn2/bazel-build/dev/contrail-telemetry-exporter:latest
      name: contrail-vrouter-telemetry-exporter
    initContainers:
    - image: svl-artifactory.juniper.net/atom-docker/cn2/bazel-build/dev/contrail-init:enable_second_interface
      name: contrail-init
    - image: svl-artifactory.juniper.net/atom-docker/cn2/bazel-build/dev/contrail-cni-init:latest
      name: contrail-cni-init
