apiVersion: v1
kind: ConfigMap
metadata:
  name: contrail-network-config
  namespace: contrail
data:
  networkConfig: |
    controlDataNetworks:
    - subnet: 10.0.0.0/24
      gateway: 10.0.0.1
    - subnet: 10.0.1.0/24
      gateway: 10.0.1.1