apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
     machineconfiguration.openshift.io/role: master
  name: 98-patch-aggregated-ca
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
      - contents:
          source: data:text/plain;charset=utf-8;base64,dW50aWwgbHMgL2V0Yy9rdWJlcm5ldGVzL2Jvb3RzdHJhcC1zZWNyZXRzL2FnZ3JlZ2F0b3ItY2EuY3J0OyBkbwogIHNsZWVwIDIKZG9uZQp1bnRpbCBscyAvZXRjL2t1YmVybmV0ZXMvYm9vdHN0cmFwLXNlY3JldHMva3ViZWNvbmZpZzsgZG8KICBzbGVlcCAyCmRvbmUKY2F0IDw8RU9GPi90bXAvcGF0Y2gKZGF0YToKICByZXF1ZXN0aGVhZGVyLWNsaWVudC1jYS1maWxlOiB8CiQod2hpbGUgSUZTPSByZWFkIC1hIGxpbmU7IGRvIGVjaG8gIiAgICAkbGluZSI7IGRvbmUgPCA8KGNhdCAvZXRjL2t1YmVybmV0ZXMvYm9vdHN0cmFwLXNlY3JldHMvYWdncmVnYXRvci1jYS5jcnQpKQpFT0YKdW50aWwgS1VCRUNPTkZJRz0vZXRjL2t1YmVybmV0ZXMvYm9vdHN0cmFwLXNlY3JldHMva3ViZWNvbmZpZyBrdWJlY3RsIC1uIGt1YmUtc3lzdGVtIHBhdGNoIGNvbmZpZ21hcCBleHRlbnNpb24tYXBpc2VydmVyLWF1dGhlbnRpY2F0aW9uIC0tcGF0Y2gtZmlsZSAvdG1wL3BhdGNoOyBkbwogIHNsZWVwIDIKZG9uZQo=
        mode: 0755
        overwrite: true
        path: /usr/local/bin/patch.sh
    systemd:
      units:
      - contents: |
          [Unit]
          Description=patch
          After=kubelet.service
          [Service]
          Type=oneshot
          ExecStart=/usr/local/bin/patch.sh
          ExecStart=systemctl daemon-reload
          [Install]
          WantedBy=multi-user.target
        enabled: true
        name: patch-aggregated-ca.service