apiVersion: configplane.juniper.net/v1alpha1
kind: Kubemanager
metadata:
  name: contrail-k8s-kubemanager
  namespace: contrail
spec:
  common:
    containers:
    - image: svl-artifactory.juniper.net/atom-docker/cn2/bazel-build/dev/contrail-k8s-kubemanager:latest
      name: contrail-k8s-kubemanager
    nodeSelector:
      node-role.kubernetes.io/master: ""
